on: push
#  pull_request:
#    branches:
#      - main
#    types: [closed]
env:
  TRELLO_KEY: ${{secrets.TRELLO_KEY}}
  TRELLO_TOKEN: ${{secrets.TRELLO_TOKEN}}
  SOURCE_LIST_ID: ${{secrets.SOURCE_LIST_ID}}
  DEST_LIST_ID: ${{secrets.DEST_LIST_ID}}

jobs:
  tag:
    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const search_url = `https://api.trello.com/1/search?key=${process.env.TRELLO_KEY}&token=${process.env.TRELLO_TOKEN}&query=test&modelTypes=cards&card_fields=url`
            console.log(search_url)
            var xmlHttp = new XMLHttpRequest();
            xmlHttp.open( "GET", theUrl, false ); 
            xmlHttp.send( null );
            console.log(xmlHttp.responseText)
            console.log(github.pull_request_review_comment)