name: Sync trello
on:
  pull_request:
    branches:
      - main
    types: closed

env:
  KEY: ${{secrets.TRELLO_KEY}}
  TOKEN: ${{secrets.TRELLO_TOKEN}}
  SOURCE_LIST_ID: ${{secrets.SOURCE_LIST_ID}}
  DEST_LIST_ID: ${{secrets.DEST_LIST_ID}}
  PULL_REQUEST_URL: ${{github.event.pull_request.html_url}}

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: ruby .github/workflows/test.rb