name: My workflow
on: [push, pull_request]

env:
  TRELLO_KEY: ${{secrets.TRELLO_KEY}}
  TRELLO_TOKEN: ${{secrets.TRELLO_TOKEN}}
  SOURCE_LIST_ID: ${{secrets.SOURCE_LIST_ID}}
  DEST_LIST_ID: ${{secrets.DEST_LIST_ID}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ruby .github/workflows/test.rb